steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/blockdawgs-server', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/blockdawgs-server']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'blockdawgs-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/blockdawgs-server'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'NODE_ENV=production'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/blockdawgs-server'

options:
  logging: CLOUD_LOGGING_ONLY
